### ISSUE TITLE
Creating questions incl. answers?

### ISSUE THREAD

**Issue by Paule2020** [VirtCode/KahootAPI#1]
Hello,
is it also possible to create questions with this API?

Why? I would like to create a "math quiz"... Simple calculations like 3+45+3 = .... or 34-50-1 and so on and the terms and solutions are created with an program and I would like to use this output to feed the API

**Comment by VirtCode** [comment]
Sorry, but this API currently only supports answering questions in running quizzes. If you want such functionality implemented, do not hesitate to create a PR.

**Comment by Paule2020** [comment]
Hi,
thanks for the answer. In the meantime I managed to feed the mongo-DB directly with questions...
